### PR TITLE
Lifecycle initial bottom tab did appear fix

### LINKED ISSUE #6880: Bottom tabs: Incorrect componentDidAppear lifecycle method being executed
## 🐛 Bug Report

When using bottom tabs, if selecting a different default tab other than the first one, its `componentDidAppear` lifecycle method is not executed. Instead, the first tab's `componentDidAppear` method is executed.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Install RNN according to the guides. `npm i react-native-navigation` and `npx rnn-link`.
2. Use the following `index.js` and `Screen.js` files.
`index.js`
```javascript
import {Navigation} from 'react-native-navigation';
import Screen from './Screen';

Navigation.registerComponent('Screen', () => Screen);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setDefaultOptions({
    bottomTab: {
      selectedTextColor: 'red',
    },
  });

  Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'BottomTabs',
        options: {
          bottomTabs: {
            currentTabId: 'Screen2',
          },
        },
        children: [
          {
            component: {
              id: 'Screen1',
              name: 'Screen',
              options: {
                bottomTab: {
                  text: 'Screen 1',
                },
              },
            },
          },
          {
            component: {
              id: 'Screen2',
              name: 'Screen',
              options: {
                bottomTab: {
                  text: 'Screen 2',
                },
              },
            },
          },
        ],
      },
    },
  });
});
```
`Screen.js`
```javascript
import React, {useEffect} from 'react';
import {Navigation} from 'react-native-navigation';
import {SafeAreaView, StyleSheet, Text} from 'react-native';

const Screen = ({componentId}) => {
  useEffect(() => {
    const unsubscribe = Navigation.events().registerComponentListener(
      {
        componentDidAppear: () =>
          console.log(`componentDidAppear ${componentId}`),
        componentDidDisappear: () =>
          console.log(`componentDidDisappear ${componentId}`),
      },
      componentId,
    );
    return () => unsubscribe.remove();
  }, [componentId]);
  return (
    <SafeAreaView style={styles.root}>
      <Text>Screen {componentId}</Text>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
  },
});

export default Screen;

```
3. Run the app with `npx react-native run-android`.
4. Observe the logs

## Expected behavior

`componentDidAppear Screen2` should have appeared in the logs

## Actual Behavior

`componentDidAppear Screen1` appeared in the logs instead.

## Your Environment

- React Native Navigation version: 7.7.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Only Android

## Reproducible Demo

[https://github.com/HectorRicardo/bugrnn](https://github.com/HectorRicardo/bugrnn)

### PR DESCRIPTION
**Pull request by swabbass**
**Issue:**
 Upon Bottom tabs creation, the initial tab set is always the first one, index=0, that caused the first tab controller onViewAppeared to be called once the root view is ready in Navigator, and then all changes that were applied got called like selecting tab, which is late to be considered as part of the bottom tabs initialization, and that treated as new action performed on bottom tabs, that triggered onViewDidAppear on non wanted views.

**Fix:**
check `currentTabId` or `currentTabIndex` from resolved options, and init bottom tabs selecting the deducted value from options or otherwise 0.

Closes #6880

### CODE REVIEW

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import android.animation.Animator;
 import android.app.Activity;
+import android.util.Log;
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java:5]:
```suggestion
```

File: lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java [hunk 2]
```diff
@@ -45,11 +46,13 @@
 import androidx.annotation.NonNull;
 import androidx.coordinatorlayout.widget.CoordinatorLayout;
 
+
 import static com.reactnativenavigation.TestUtils.hideBackButton;
 import static com.reactnativenavigation.utils.ObjectUtils.perform;
 import static org.assertj.core.api.Java6Assertions.assertThat;
 import static org.mockito.ArgumentMatchers.any;
 import static org.mockito.ArgumentMatchers.eq;
+import static org.mockito.Mockito.reset;
```
Comment (yogevbd) [inline lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java:55]:
```suggestion
```

**Review by yogevbd — CHANGES_REQUESTED** [review]

**Review by yogevbd — APPROVED** [review]
