### PR TITLE
Fix autolink for RN 0.69

### LINKED ISSUE #7564: npx rnn-link not updating App Delegate correctly (RN 0.69.2 - RNN 7.28.1)
## 🐛 Bug Report

npx rnn-link script must remove RCTAppSetupRootView. It's breaking RNN.

## To Reproduce

1. npx react-native init AwesomeProject // 0.69.2
2. npm install --save react-native-navigation
3. pod install --project-directory=ios
4. npx rnn-link

## Expected behavior

I expect script to remove lines correctly from app.delegate,mm file.
Following lines are not removed and it's breaking the navigation.

Screen Shot 2022-07-21 at 22 15 01

Since they are executed after rnn's registered, app throws following errors and if I dismiss it, it partially works.

```console
has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

Script requires an update. Those 2 lines must be removed. 

## Your Environment

"react-native": "0.69.2",
"react-native-navigation": "^7.28.1",
IOS

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### PR DESCRIPTION
**Pull request by gaguirre**
This PR updates autolink script for both Android and iOS to make them compatible with RN 0.69
It should fix #7564 and also tackle an issue commented in #7547

I've also added some snapshot tests for the modified files (`activityLinker.js` and `appDeletegateLinker.js`). In order to do so, some fixtures were added: `MainActivity.java` and `AppDelegate.mm` files for RN 0.68 and 0.69

These tests execution is included in `test-all` command, but could be removed if necessary.

### CODE REVIEW

File: autolink/postlink/appDelegateLinker.js [hunk 1]
```diff
@@ -153,7 +153,11 @@ class AppDelegateLinker {
       /rootViewController\.view\s+=\s+rootView;\s+/,
       /self.window.rootViewController\s+=\s+rootViewController;\s+/,
       /\[self.window\s+makeKeyAndVisible];\s+/,
+      // Added from RN 0.69
+      /NSDictionary\s+\*initProps\s+=\s+\[self prepareInitialProps];\s+/,
+      /UIView \*rootView = RCTAppSetupDefaultRootView\(bridge, @".*", initProps\);/,
```
Comment (yogevbd) [inline autolink/postlink/appDelegateLinker.js:158]: I don't think we need this as we construct the views within RNN

Comment (gaguirre) [reply autolink/postlink/appDelegateLinker.js:158]: Yes, with `Added from RN 0.69` comment I meant these are _new lines to be removed_.

**Review by yogevbd — APPROVED** [review]
