### PR TITLE
Fixes #5888 Cannot change swipeToDismiss through mergeOptions

### LINKED ISSUE #5888: Cannot change swipeToDismiss through mergeOptions
### Issue Description

It does not seem to be possible to change the value of `swipeToDismiss` through `mergeOptions`. Looking at the Code of `RNNBasePresenter.m`, it looks like the option is only used in `applyOptionsOnInit`.

Not sure if iOS allows you to change it after the view is created, but if it doesn't, it should at least be documented.

### Steps to Reproduce / Code Snippets / Screenshots

```js
componentDidMount() {
  Navigation.mergeOptions(this.props.componentId, {
    modal: {
      swipeToDismiss: false,
    }
  });
}
```

---
### Environment
* React Native Navigation version: 4.2.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

### PR DESCRIPTION
**Pull request by cHaLkdusT**

### CODE REVIEW

File: lib/ios/RNNBasePresenter.m [hunk 1]
```diff
@@ -71,10 +71,14 @@ - (void)applyOptions:(RNNNavigationOptions *)options {
 - (void)mergeOptions:(RNNNavigationOptions *)options resolvedOptions:(RNNNavigationOptions *)resolvedOptions {
     RNNNavigationOptions* withDefault = (RNNNavigationOptions *) [[resolvedOptions withDefault:_defaultOptions] overrideOptions:options];
 	
-	if (options.window.backgroundColor.hasValue) {
-		UIApplication.sharedApplication.delegate.window.backgroundColor = withDefault.window.backgroundColor.get;
-	}
-    
+    if (@available(iOS 13.0, *)) {
+        self.boundViewController.modalInPresentation = ![withDefault.modal.swipeToDismiss getWithDefaultValue:YES];
```
Comment (yogevbd) [inline lib/ios/RNNBasePresenter.m:75]:
```suggestion
    if (@available(iOS 13.0, *)) {
        if (withDefault.modal.swipeToDismiss.hasValue) self.boundViewController.modalInPresentation = !withDefault.modal.swipeToDismiss.get;
```

**Review by yogevbd — DISMISSED** [review]

**Review by guyca — APPROVED** [review]
