### PR TITLE
Fix buttons tint color on iOS 12

### LINKED ISSUE #6877: 7.7.0 regression with TopBar button color on IOS 12
## 🐛 Bug Report

When upgrading from version 7.6.0 to 7.7.0, it appears that setting colors for left/right buttons in the TopBar no longer works. I have tried setting them with both the topBar.leftButtonColor/rightButtonColor options as well as the individual color option on each button with the same effect. This doesn't appear to happen on IOS13.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Load a nav button icon to use (from react-native-svg or similar)
2. Construct a component in the following manner with a custom button color:
```  component: {
        name: 'My.Screen',
        options: {
          topBar: {
            title: {
              text: `Campaigns`,
            },
            rightButtonColor: '#888888',
            rightButtons: [{
              icon: iconsMap.add,
              id: 'add',
              color: '#888888',
              accessibilityLabel: 'New Campaign',
            }],
          },
        },
      },
    }; 
 ```
3. Observe that the buttons remain 'navigation' blue on iOS 12 simulator/real devices.

## Expected behavior

Expected the buttons change to the specified color.

## Actual Behavior

Buttons remain navigation blue (default)

## Your Environment

- React Native Navigation version: 7.7.0
- React Native version: 0.63.4
- Platform: iOS
- Device info: Simulator/Real device running IOS 12

## Reproducible Demo

Can create one if necessary, but seems fairly easy to reproduce with any existing project.

### PR DESCRIPTION
**Pull request by yogevbd**
Fixes a regression created in [this commit](8131ea7650b997cbaefa2665fcad039005ae6955) which caused buttons with icon to never receive a tint color on iOS 12.

Closes #6877

### CODE REVIEW

File: lib/ios/RNNUIBarButtonItem.m [hunk 1]
```diff
@@ -125,6 +125,7 @@ - (void)applyOptions:(RNNButtonOptions *)buttonOptions {
     self.accessibilityLabel = [buttonOptions.accessibilityLabel withDefault:nil];
     self.enabled = [buttonOptions.enabled withDefault:YES];
     self.accessibilityIdentifier = [buttonOptions.testID withDefault:nil];
+    self.tintColor = [buttonOptions.color withDefault:nil];
```
Comment (zzorba) [inline lib/ios/RNNUIBarButtonItem.m:128]: Seems like this might want to be `getWithDefaultValue:nil` instead of `withDefault:nil` -- ran into a compilation issue without it.

**Review by zzorba — CHANGES_REQUESTED** [review]
Looks like there is a minor compilation issue.

That said, I can confirm that when changed to use `getWithDefaultValue:nil` the behavior is fixed on IOS12 (also confirmed that IOS13 continues to work).

File: lib/ios/RNNUIBarButtonItem.m (hunk 1 above)
Comment (yogevbd) [reply lib/ios/RNNUIBarButtonItem.m:128]: I renamed `getWithDefaultValue` to `withDefault`  [here](4a5b8a4ac44c4a3c6a0c81fa13e8aaf284c4c983). The next RNN version will include this fix.

Comment (zzorba) [reply lib/ios/RNNUIBarButtonItem.m:128]: Oh totally missed that, thank you!

**Review by zzorba — APPROVED** [review]
Can confirm fix, thank you for the quick change!

**Review by zzorba — APPROVED** [review]

**Comment by radiosilence** [comment]
I do not think disabling tinting works now?

**Comment by tastyqbit** [comment]
@yogevbd Is there any update on why disabled tint on topbar buttons has stopped working?
