### PR TITLE
Fix backButton properties on iOS

### LINKED ISSUE #3454: [v2] `topBar.buttonColor` is ignored for back button
```
topBar: {
  buttonColor: 'red'
}
```

Did not work, but 

```
backButton: {
  color: 'red'
}
```

Did

### LINKED ISSUE #3731: [V2][iOS] Cannot set back button color
### Issue Description

When changing color of the back button of the `topBar` you define the styles like so:
```
Navigation.setDefaultOptions({
  topBar: {
    backButton: { color: '#ffffff' }, // Android
    buttonColor: '#ffffff', // iOS
  },
});
```

This works up to RNN version `2.0.2461`. But version `2.0.2462` onwards back button color is broken on iOS.

Looks like the only way to color your back button is to provide `icon` like this:
```
Navigation.setDefaultOptions({
  topBar: {
    backButton: { color: '#ffffff', icon: require('./images/someIcon.png') },
  },
});
```

But this is not ideal solution for people who want to use the default icon.

I am pretty sure these commits are related: https://github.com/wix/react-native-navigation/commit/98ff69ec562108f6b1e627804c52655494012d21 https://github.com/wix/react-native-navigation/commit/7cf172a364f6dcc17728c3e9e875f964ba679eb2

Ping @guyca @yogevbd 

---
### Environment
* React Native Navigation version: 2.0.2462
* React Native version: 0.54.4
* Platform(s): iOS
* Device info: Real iPhone 6s

### PR DESCRIPTION
**Pull request by henrikra**
This PR fixes `backButton` properties on iOS. Previously for example `color` prop didn't work.
I made the `RNNBackButtonOptions.m` file simple as possible because now it was too complicated. @guyca Please tell if I deleted something that shouldn't been removed 😉 

## Demos

```typescript
Navigation.setDefaultOptions({
  topBar: {
    backButton: {},
  },
});
```
image

```typescript
Navigation.setDefaultOptions({
  topBar: {
    backButton: { color: 'red' },
  },
});
```

image

```typescript
Navigation.setDefaultOptions({
  topBar: {
    backButton: { showTitle: false },
  },
});
```
image

```typescript
Navigation.setDefaultOptions({
  topBar: {
    backButton: { title: 'Henrik' },
  },
});
```

image

```typescript
Navigation.setDefaultOptions({
  topBar: {
    backButton: { icon: require('./images/shoppingCart.png') },
  },
});
```

image

```typescript
Navigation.setDefaultOptions({
  topBar: {
    backButton: {
      icon: require('./images/shoppingCart.png'),
      color: 'red',
    }
  },
});
```

image

## Before merging
Guys help to get this in and actually TEST this on your app and post the results to the comments <3

Fixes #3454
Fixes #3731

### CODE REVIEW

**Comment by henrikra** [comment]
@rgoldiez @bemazo @heroic @chrise86 @guyca Can you guys check this out :)

**Comment by rgoldiez** [comment]
@henrikra - This is great!!  It's working for me.

**Comment by heeroduo** [comment]
May I know how I can test it? I modified the file 'RNNBackButtonOptions.m' and saved. and then I launched my app again by 'react-native run-ios' but it still doesn't work. maybe I did something wrong. May I know the right way to test this code?

**Comment by chrise86** [comment]
I haven’t _tried_ it yet, but on the surface it looks promising, and very similar to something I started the other day. I was working on adding `tintColor` to the topBar which would have set the back button colour, but I think this is better as `tintColor` is very much an iOS thing, and this API should be as platform agnostic as possible, IMO.

**Comment by henrikra** [comment]
@chrise86 Great! Tell me the results when you have time :)

**Comment by oldtinroof** [comment]
This was working for me until xcode updated to the latest version 🤕 
Now the colour change is no longer controllable with this fix.

Have you got any ideas why this might be?

**Comment by oldtinroof** [comment]
Sorry, @henrikra, this seems to be not working with the latest version either.  I'm gutted, as I'm about a day or so away from app store submission on this app, and the back button colour is the only thing stopping us from releasing :(

**Comment by oldtinroof** [comment]
The branch doesn't have a lib/dist folder - so it won't load in my app - I've not got time this evening to build it locally, so will pick this back up again tomorrow at some point. Cheers @henrikra - I'm sure it'll be something small I've missed!

**Comment by henrikra** [comment]
@oldtinroof Easiest way to test this without any branch hassle is to open file `node_modules/react-native-navigation/lib/ios/RNNBackButtonOptions.m` in your current project and replace the file content with my file's content. Then rebuild your app (refresh is not enough)

**Comment by chrise86** [comment]
This is working great for me on Xcode 9. Installing Xcode 10 now and will try again to see if I get the same issue as @oldtinroof.

**Comment by henrikra** [comment]
@chrise86 What whitespace you are talking about?

**Comment by oldtinroof** [comment]
Hi @henrikra - turns out I'd not noticed that Xcode 10 had defaulted to an older iOS version on the simulator - 10.3.1

Once I started using 11.4 or 12.0 the patch works again.  Apologies for the confusion! And thanks for sorting it out :)

**Comment by chrise86** [comment]
@henrikra just a mixture of spaces and tabs, nothing major - I'm just a stickler for code quality ;)

File: lib/ios/RNNBackButtonOptions.m [hunk 1]
```diff
@@ -4,46 +4,41 @@
 @implementation RNNBackButtonOptions
 
 - (void)applyOn:(UIViewController *)viewController {
-	if (self.showTitle && ![self.showTitle boolValue]) {
-		self.title = @"";
+  	UIBarButtonItem *backItem = [[UIBarButtonItem alloc] init];
+  
+	backItem.image = self.tintedIconIfAvailable;
```
Comment (yogevbd) [inline lib/ios/RNNBackButtonOptions.m]: The system back button should be hidden when you are using an icon. 
We need to add this code in case `self.tintedIconIfAvailable` return value
```
[viewController.navigationController.navigationBar setBackIndicatorImage:[UIImage new]];	
[viewController.navigationController.navigationBar setBackIndicatorTransitionMaskImage:[UIImage new]];
```
Thanks! great PR

**Comment by henrikra** [comment]
@yogevbd Thank you for the fixes!
