### PR TITLE
Fix large title presentation

### LINKED ISSUE #5418: [V2] Crash when returning to root by pressing Bottom Tab on iOS
### Issue Description

When I press a bottom tab after pushing two screens onto the stack for that tab, the app crashes. 

### Steps to Reproduce / Code Snippets / Screenshots

1. Start a tab based app where the root screen for one of the tabs has buttons in the TopBar
2. Push a screen on to that tab, and then push another screen on top of that.
3. Press the Bottom Tab for that screen, crash will happen.

Interestingly, if I push a third or fourth screen before pressing the bottom tab, there is no crash.

Native Crash Log: 
```
2019-08-27 17:01:05.869215-0600 Homepass[49690:950985] -[_UIBackButtonContainerView titleLabel]: unrecognized selector sent to instance 0x7faab9a187c0
2019-08-27 17:01:05.874613-0600 Homepass[49690:950985] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UIBackButtonContainerView titleLabel]: unrecognized selector sent to instance 0x7faab9a187c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001176a76fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000116018ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001176c5ab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00000001217adc3d -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x00000001176ac443 ___forwarding___ + 1443
	5   CoreFoundation                      0x00000001176ae238 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x0000000120f4bed8 _titleTransitionAdjustmentFromLargeTitleToBackButton + 170
	7   UIKitCore                           0x0000000120f4f4c8 -[_UINavigationBarTransitionContextPop _prepareScaleTransition] + 197
	8   UIKitCore                           0x0000000120f4fe7d -[_UINavigationBarTransitionContextPop prepare] + 146
	9   UIKitCore                           0x0000000120f72772 -[_UINavigationBarVisualProviderModernIOS _performAnimationWithTransitionCompletion:transition:] + 966
	10  UIKitCore                           0x0000000120f22998 -[UINavigationBar _setItems:transition:reset:resetOwningRelationship:] + 2004
	11  UIKitCore                           0x0000000120f21fe3 -[UINavigationBar setItems:animated:] + 225
	12  UIKitCore                           0x00000001210cbb72 __80-[UINavigationController _setViewControllers_7_0:transition:animated:operation:]_block_invoke + 481
	13  UIKitCore                           0x00000001210cbd6b __80-[UINavigationController _setViewControllers_7_0:transition:animated:operation:]_block_invoke.539 + 114
	14  UIKitCore                           0x00000001210e2725 __98-[UINavigationController _shouldSkipHostedRefreshControlUpdateSchedulingDeferredUpdateIfNecessary]_block_invoke + 16
	15  UIKitCore                           0x00000001210e4599 -[UINavigationController _startDeferredTransitionIfNeeded:] + 1380
	16  UIKitCore                           0x00000001210e56a7 -[UINavigationController __viewWillLayoutSubviews] + 150
	17  UIKitCore                           0x00000001210c638d -[UILayoutContainerView layoutSubviews] + 217
	18  UIKit                               0x0000000139aefa87 -[UILayoutContainerViewAccessibility layoutSubviews] + 42
	19  UIKitCore                           0x0000000121c4f9c1 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1417
	20  QuartzCore                          0x0000000113cabeae -[CALayer layoutSublayers] + 173
	21  QuartzCore                          0x0000000113cb0b88 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 396
	22  QuartzCore                          0x0000000113cbcee4 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 72
	23  QuartzCore                          0x0000000113c2c3aa _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 328
	24  QuartzCore                          0x0000000113c63584 _ZN2CA11Transaction6commitEv + 608
	25  QuartzCore                          0x0000000113c63ede _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	26  CoreFoundation                      0x000000011760e0f7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	27  CoreFoundation                      0x00000001176085be __CFRunLoopDoObservers + 430
	28  CoreFoundation                      0x0000000117608c31 __CFRunLoopRun + 1505
	29  CoreFoundation                      0x0000000117608302 CFRunLoopRunSpecific + 626
	30  GraphicsServices                    0x000000011b0592fe GSEventRunModal + 65
	31  UIKitCore                           0x0000000121781ba2 UIApplicationMain + 140
	32  Homepass                            0x000000010ef5e6d0 main + 112
	33  libdyld.dylib                       0x00000001193f3541 start + 1
	34  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

---
### Environment
* React Native Navigation version: 2.27.2
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 12, Debug

### PR DESCRIPTION
**Pull request by yogevbd**
Closes #5418

### CODE REVIEW

**Comment by yogevbd** [comment]
Closes #5984

File: lib/ios/RNNStackPresenter.m [hunk 1]
```diff
@@ -62,7 +62,7 @@ - (void)applyOptions:(RNNNavigationOptions *)options {
     [_topBarPresenter applyOptions:withDefault.topBar];
     
     [stack setNavigationBarBlur:[withDefault.topBar.background.blur getWithDefaultValue:NO]];
-    [stack setNavigationBarLargeTitleVisible:[withDefault.topBar.largeTitle.visible getWithDefaultValue:NO]];
```
Comment (guyca) [inline lib/ios/RNNStackPresenter.m]: How come we don't need to pass a value to `setNavigationBarLargeTitleVisible` anymore?

File: lib/ios/TopBarPresenter.m [hunk 2]
```diff
@@ -112,18 +112,21 @@ - (void)setLargeTitleAttributes:(RNNLargeTitleOptions *)largeTitleOptions {
 }
 
 - (void)setBackButtonOptions:(UIImage *)icon withColor:(UIColor *)color title:(NSString *)title showTitle:(BOOL)showTitle fontFamily:(NSString *)fontFamily fontSize:(NSNumber *)fontSize {
-	UIBarButtonItem *backItem = [[UIBarButtonItem alloc] init];
-    NSArray* stackChildren = self.navigationController.viewControllers;
+	NSArray* stackChildren = self.navigationController.viewControllers;
+    UIViewController *lastViewControllerInStack = stackChildren.count > 1 ? stackChildren[stackChildren.count - 2] : self.navigationController.topViewController;
```
Comment (guyca) [inline lib/ios/TopBarPresenter.m]: If the stack has a single child, we set the back button text from the single child it contains. But it doesn't have a back button in this case - so why run this logic if `count <= 1` ?
