### PR TITLE
Android API 30 fixes

### LINKED ISSUE #4258: [V2]Immersive mode
### Issue Description

I am trying to enter immersive mode when app starts but the screen won't redraw over the part where the navigation bar dissapeared

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?):Android
* Device info (Simulator/Device? OS version? Debug/Release?): Google Pixel 2

### LINKED ISSUE #6988: StatusBar hidden with drawBehind causes content to jump
## 🐛 Bug Report

Screen A has:

```
statusBar: {
  visible: true,
  drawBehind: true,
}
```

Screen B has:

```
statusBar: {
  visible: false,
  drawBehind: true,
}
```

This works fine on iOS but causes the content to jump on some Android devices.

Note: I say _some_ because this issue only affects Android devices where the StatusBar is larger than `24` pixels. (e.g. phones with notches, ..)

https://user-images.githubusercontent.com/15199031/108871097-16842e80-75f9-11eb-880f-4dd66a1c1330.mp4

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## To Reproduce

1. Create Screen A and B from above
2. Navigate from Screen A to Screen B using `showModal`

## Expected behavior

I expect the statusBar visible: false prop to not affect the `drawBehind` property, aka the content should not jump

(Write what you thought would happen.)

## Actual Behavior

The content jumps. See demo video

## Your Environment

- React Native Navigation version: 7.8.4-snapshot.1439
- React Native version: 0.64.0-rc.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): All Android phones with StatusBar height > `24`

### LINKED ISSUE #7111: Shared Element Transition broken with safe area
## 🐛 Bug Report

The Shared Element Transition seems to not animate to the correct bounds.

Here's a video of the SET breaking on a phone that has left and right "edges" 

https://user-images.githubusercontent.com/15199031/117459200-6eb9a400-af4b-11eb-83a6-1cfda49d6711.mp4

In this case I think the problem is that the screen absolute coordinates are used, which are not equal to the coordinates relative to the React Root view and they extend beyond those screen "edges":

(just assuming things here)

Here's another case of the bounds animation failing, this is a regular phone without any "safe areas", just the 24px statusbar:

https://user-images.githubusercontent.com/15199031/117459759-0a4b1480-af4c-11eb-84ae-1e5e34049c97.MP4

Here the image seems to be a bit higher up than it should be, looks to me as if it were exactly twice the statusbar moved up. Maybe there's a `- STATUS_BAR_HEIGHT` somewhere where it should be a `+ STATUS_BAR_HEIGHT` instead, just assuming things again. You can also see that after I fast-refresh the view, it goes into the correct place, so it has to be an issue with the RNN SET.

Maybe `statusBar: { drawBehind: true }` or `statusBar: { visible: false }` is not respected here?

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yea

## To Reproduce

1. Create Shared Element Transition
1. Try it on phones with Safe Areas, or in my case just a regular Huawai P10

## Expected behavior

It should exactly animate to the bounds of the target react view

## Actual Behavior

it animates to some wrong coordinates.

## Your Environment

- React Native Navigation version: 6f7c2d9f75b5fb653452f903d822429eed429f51
- React Native version: 0.64.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): all

### LINKED ISSUE #7171: [Android] Screen size not adjusted properly when navigationBar is hidden
## 🐛 Bug Report

Screen size remains the same size when navigationBar is hidden, leaving a background colored box where the navigationBar used to be.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. Start with playground app
2. In app.ts, edit the setRoot() call so that that the Options stack is directly below root, removing bottomTabs and the other screens
3. Start the app, click the "Toggle Navigation bar visibility" button

## Expected behavior
The usable screen should expand towards the bottom when the navigation bar disappears. This works when using the bottomBar.

## Actual Behavior
The navigation bar disappears, but the area remains unusable. Scrolling the view moves the buttons under the navigation bar area instead of letting them hit the bottom of the screen.

Attached are screenshots showing the situation.

scrolled_down
scrolled_up

## Your Environment

- React Native Navigation version: 7.16.0
- React Native version: 0.63.1
- Platform: Only tested on Android
- Device info: Android 8.1 simulated and device

## Reproducible Demo

```
git clone https://github.com/hooplab/react-native-navigation.git rnn_navbar
cd rnn_navbar
git checkout navbar_bug
```

Follow [Playground instructions](https://wix.github.io/react-native-navigation/docs/playground-app) to start app

### LINKED ISSUE #7199: Hiding the bottom navigation bar on Android creates a gap at the bottom of the view
## 🐛 Bug Report

When the navigation bar is set to `visible: false` (as described [here](https://wix.github.io/react-native-navigation/api/options-navigationBar#visible)), it still takes up space. Nothing is able to render in the gap.

Screen Shot 2021-07-21 at 2 32 04 PM

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. Clone the demo (link below)
2. `cd navigation-bar-demo`
3. `yarn install`
4. `react-native run-android`

If the blue background doesn't appear on the first run, you may need to run `react-native run-android` a second time.

## Expected behavior

The blue background should extend all the way to the bottom of the view.

## Actual Behavior

The blue background stops where the navigation bar would be if it were visible.

## Your Environment

- React Native Navigation version: 7.17.1
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android 11 on Pixel 4 Emulator

## Reproducible Demo

https://github.com/dillpixel/navigation-bar-demo

### LINKED ISSUE #7225: Android targetSdkVersion 30 breaks overlay style
## 🐛 Bug Report

When targeting Android sdk version 30 some overlays that should be shown in full screen are not. 

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes, I've read the guidelines. 

## To Reproduce

1. Clone the react-native-navigation repo `git clone https://github.com/wix/react-native-navigation.git`
2. Go to the cloned folder and install dependencies `cd react-native-navigation && npm install --legacy-peer-deps`
3. Start the packager `npm run start`
4. Open the playground android app in Android studio
5. Change the `targetSdkVersion` and `compileSdkVersion` to `30` in the `./playground/android/app/build.gradle` file
6. Build and run the playground app
7. Go to the `Navigation` tab
8. Press the `Overlay` button
9. Press the `Alert` button
10. Alert and backdrop are displayed offset by about 44-45px from the top

## Expected behavior

Alert and backdrop should be correctly centred.

## Actual Behavior

Alert and backdrop are offset by about 44-45px from the top

Screenshot 2021-08-20 at 23 14 28

## Your Environment

Issue appears only when targeting sdk 30, sdk 29 works as intended.

Screenshot 2021-08-20 at 22 08 40

The issue also appears in modals but I've not been able to reproduce it in the playground app.  
In our own project the following code shows a broken modal (same 44-45px offset):
```typescript
Navigation.showModal({
  component: {
    name: 'componentName',
  }
})
```
While the following code correctly shows the modal:
```typescript
Navigation.showModal({
  stack: {
    children: [
      {
        component: {
          name: 'componentName',
        },
      },
    ],
  },
})
```

I wasn't able to find any workaround for the overlays.  

- React Native Navigation version: 7.18.0
- React Native version: 0.63.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Pixel4XLAPI30 simulator in Debug

## Reproducible Demo

React-Native-Navigation playground app is presenting the issue

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

### LINKED ISSUE #7339: statusBar is black with translucent true option when showOverlay on some Android devices
## 🐛 Bug Report

showOverlay with statusBar translucent true, makes statusBar black on some Android devices

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## Expected behavior

statusBar has correct color

telegram-cloud-photo-size-2-5195033218670245126-y

## Actual Behavior

statusBar is black 

screenshot

## Your Environment

- React Native Navigation version: 7.23.1
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android 6.0.1
- Device info (Simulator/Device? OS version? Debug/Release?): Readme Note 3

### LINKED ISSUE #7358: Android - cannot dismissOverlay when it contains a stack
## 🐛 Bug Report

I'm trying to workaround the Android API 30 bugs : https://github.com/wix/react-native-navigation/issues/7225

To do so, I wrap my overlay's components in a stack. The layout issue is gone but when doing so, I cannot dismiss the overlay...

## To Reproduce

Add somewhere in your code:

    Navigation.showOverlay({ stack: { children: [ MyScreen ]  } });

Then, in MyScreen code, add:

    Navigation.dismissOverlay(props.componentId); // that will have no effect except a warning for unhandled promise...

## Expected behavior

This:

    Navigation.dismissOverlay(props.componentId);  

...  should work even when overlay contain a stack.

## Actual Behavior

This: 

    Navigation.dismissOverlay(props.componentId);  

... does not work when the overlay contains a stack.

## Your Environment

- React Native Navigation version: 7.12.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): both

### LINKED ISSUE #7360: Status Bar - Overlay cut due to upgrade targetSDKversion upgate to 29 to 30
WhatsApp Image 2021-11-20 at 12 46 47 PM

Top status bar cut when overlay open see above screenshot

and make changes below
Screenshot 2021-11-19 at 7 06 34 PM

I tried to set status bar value as below but not working and also upgrade lib 7.16.0 to 7.23.1 and then try below solution but not working and I have tested this in my redmi note 8 pro mobile
statusBar: {
        visible: false,
        drawBehind: true,
        translucent: false,
      }

### PR DESCRIPTION
**Pull request by swabbass**
Upgrading android target SDK to 30, to support android 12 changes.

- Refactor StatusBarUtil to SystemUIUtils to include status and navigation bars.
- Migrate deprecated code using flags to a modern one.
- Calculating WindowInsets per component where all views are laid as full screen.
- Keyboard enhancements to show hide keyboard.
- Fix applying Options of a child taking parent Options into consideration.
- Fix fixed status bar height and use a more elegant way.
- Add more tests for SystemUiUtils.
- Add a SystemUi screen to demonstrate system UI capabilities.
- Migrate Reanimated usage to support Reanimated 2.

Closes #7339.
Closes #7225.
Closes #7358.
Closes #7199.
Closes #7171.
Closes #7111.
Closes #6988.
Closes #4258.
Closes #7360.

Demo:

https://user-images.githubusercontent.com/7227793/142203865-d65b6910-21f8-4617-812e-b5576a6b58e4.mov

### CODE REVIEW

**Comment by Batistleman** [comment]
Can we help with something to get this merged? (Due to Play store changes this is blocking for new app releases)
Screenshot 2021-11-23 at 12 06 00

**Comment by swabbass** [comment]
@Batistleman this week will be merged and release a new version. stay tuned.

File: lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+                val statusBarHeight: Int = rectangle.top
+                val contentView = window.findViewById<View>(Window.ID_ANDROID_CONTENT)
+                contentView?.let {
+                    val contentViewTop = contentView.top
+                    abs(contentViewTop - statusBarHeight)
+                }
+            } ?: if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) STATUS_BAR_HEIGHT_M else STATUS_BAR_HEIGHT_L
+            statusBarHeight
+        }
+        logd("StatusBarHeight $res", "STATUSXXXX")
```
Comment (swabbass) [inline lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt:44]:
```suggestion
```

**Comment by thuongtv-vn** [comment]
@swabbass 

Do you have any idea to apply this with RN v63? Or at least RN v66 is required?

**Comment by marf** [comment]
Could this be merged and a new RNN version released please?

**Comment by swabbass** [comment]
As it seems, we are facing a couple of issues with status bar icon colours on android 30, sorry for the inconvenience, but we are working hard to deliver a fully baked solution.

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java [hunk 2]
```diff
@@ -244,24 +244,38 @@ private void applyTopBarOptions(Options options, StackController stack, ViewCont
...
-    private void mergeStatusBarDrawBehindOptions(TopBarOptions topBarOptions, Options toMerge) {
-        if (toMerge.statusBar.drawBehind.hasValue()) {
-            if (toMerge.statusBar.visible.isTrueOrUndefined() && toMerge.statusBar.drawBehind.isTrue()) {
-                topBar.setTopPadding(StatusBarUtils.getStatusBarHeight(activity));
-                topBar.setHeight(topBarOptions.height.get(UiUtils.getTopBarHeightDp(activity)) + StatusBarUtils.getStatusBarHeightDp(activity));
-            } else {
-                topBar.setTopPadding(0);
-                topBar.setHeight(topBarOptions.height.get(UiUtils.getTopBarHeightDp(activity)));
+    
+    private void mergeStatusBarDrawBehindOptions(TopBarOptions topBarOptions, Options childOptions) {
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java:256]: look like this code does the same thing, maybe we shouldn't touch it?

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/child/ChildController.java [hunk 3]
```diff
@@ -61,19 +67,22 @@ public void onViewDisappear() {
...
     }
 
     @Override
     public void applyOptions(Options options) {
         super.applyOptions(options);
-        presenter.applyOptions(this, resolveCurrentOptions());
+        final ParentController<?> parentController = getParentController();
+        final Options resolveCurrentOptions = parentController == null ? resolveCurrentOptions() :
+                parentController.resolveChildOptions(this);
+        presenter.applyOptions(this, resolveCurrentOptions);
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/child/ChildController.java:79]: maybe we should have this fix in another PR?

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java [hunk 4]
```diff
@@ -485,16 +498,18 @@ private void mergeBackButton(TopBarButtons buttons, StackController stack) {
...
-        if (options.layout.direction.hasValue()) topBar.setLayoutDirection(options.layout.direction);
+        if (toMerge.layout.direction.hasValue()) topBar.setLayoutDirection(toMerge.layout.direction);
         if (topBarOptions.height.hasValue()) topBar.setHeight(topBarOptions.height.get());
         if (topBarOptions.elevation.hasValue()) topBar.setElevation(topBarOptions.elevation.get());
         if (topBarOptions.topMargin.hasValue() && topBar.getLayoutParams() instanceof MarginLayoutParams) {
             ((MarginLayoutParams) topBar.getLayoutParams()).topMargin = UiUtils.dpToPx(activity, topBarOptions.topMargin.get());
         }
-        mergeStatusBarDrawBehindOptions(resolveOptions, options);
+        Options childOptions = stack.resolveChildOptions(child).mergeWith(toMerge).withDefaultOptions(defaultOptions);
+        mergeStatusBarDrawBehindOptions(resolveOptions, childOptions);
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java:512]: this one as well

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/child/ChildController.java (hunk 3 above)
Comment (swabbass) [reply lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/child/ChildController.java:79]: agree!

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java (hunk 4 above)
Comment (swabbass) [reply lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java:512]: Since topBar position depends on status bar options we need to merge those options and have them every time we need to update the topBar position we need the current options state of the status bar, taking into consideration the child options and the options that passed to `mergeOptions` and default options, this was done in the calling function `mergeTopBarOptions` but it's done for the topBar options only, and changing the calling function arguments would cause another changes across the files and the tests.

think we might leave it as is, and the next PR that deals with options aggregation will have proper change.

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java (hunk 2 above)
Comment (swabbass) [reply lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java:256]: it has missing use cases, when applying options (initial top bar position) the code is alright, but when changing the position we need to take into consideration more cases, see the differences, each toggle is a `mergeOptions` with a single option change:

old code:


https://user-images.githubusercontent.com/7227793/143925712-fd70a1a4-cc82-4e40-abe2-a141d8b20b35.mov

new code:


https://user-images.githubusercontent.com/7227793/143925808-12c62c32-dd4b-4420-9934-04576bd30b1e.mov

**Review by yogevbd — APPROVED** [review]

**Comment by Ivan-okolzin** [comment]
Hi everyone! Please tell me, when will it be released?

**Comment by yogevbd** [comment]
@Ivan-okolzin hi, we plan to release this today
