### PR TITLE
Fix sidemenu drawer width support‏

### LINKED ISSUE #5165: Unable to change width of sideMenu with mergeOptions() method
### Issue Description

I try to dinamically change width of sideMenu, but not works. This is implemented? If not, would be useful to improve usability with large width devices (eg.: setting menu width when orientation changes). 

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.mergeOptions(this.props.componentId, {
   sideMenu: {
     left: {
       width: 300
     }
   }
});
```

---
### Environment
* React Native Navigation version: v2.21.0
* React Native version: v0.59.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Android 5, Android 8 and iPhone 5

### PR DESCRIPTION
**Pull request by lionerez1**
* Fix initial width from options
* Fix change width by mergeOptions

Closes #5165‏

### CODE REVIEW

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuPresenter.java [hunk 1]
```diff
@@ -82,6 +97,28 @@ private void mergeLockMode(SideMenuRootOptions options) {
...
+            left.getView().getLayoutParams().width = (int) TypedValue.applyDimension(
+                    TypedValue.COMPLEX_UNIT_DIP,
+                    sideMenuRootOptions.left.width.get(),
+                    Resources.getSystem().getDisplayMetrics());
+
+            left.getView().requestLayout();
+        }
+    }
+
+    private void handleRightWith(SideMenuRootOptions sideMenuRootOptions) {
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuPresenter.java:111]:
```suggestion
    private void applyRightWidth(SideMenuRootOptions sideMenuRootOptions) {
```

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuPresenter.java [hunk 2]
```diff
@@ -41,6 +54,8 @@ public void mergeOptions(SideMenuRootOptions options) {
     public void applyChildOptions(Options options) {
         applyLockMode(options.sideMenuRootOptions);
         mergeVisibility(options.sideMenuRootOptions);
+        handleLeftWidth(options.sideMenuRootOptions);
+        handleRightWith(options.sideMenuRootOptions);
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuPresenter.java:58]:
```suggestion
        applyLeftWidth(options.sideMenuRootOptions);
        applyRightWidth(options.sideMenuRootOptions);
```

File: lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuPresenter.java [hunk 3]
```diff
@@ -82,6 +97,28 @@ private void mergeLockMode(SideMenuRootOptions options) {
         }
     }
 
+    private void handleLeftWidth(SideMenuRootOptions sideMenuRootOptions) {
```
Comment (yogevbd) [inline lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuPresenter.java:100]:
```suggestion
    private void applyLeftWidth(SideMenuRootOptions sideMenuRootOptions) {
```

**Review by yogevbd — CHANGES_REQUESTED** [review]

**Review by yogevbd — APPROVED** [review]
