### PR TITLE
Fix animation callback crash after setStackRoot and push

### LINKED ISSUE #6071: Tried to create view after it has already been destroyed
### Issue Description

Tried to create view after it has already been destroyed

### Stack trace

```
java.lang.RuntimeException: Tried to create view after it has already been destroyed
    at com.reactnativenavigation.viewcontrollers.ViewController.getView(ViewController.java:195)
    at com.reactnativenavigation.viewcontrollers.ChildController.getView(ChildController.java:35)
    at com.reactnativenavigation.anim.NavigationAnimator$1.onAnimationEnd(NavigationAnimator.java:60)
    at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
    at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
    at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
    at android.view.Choreographer.doCallbacks(Choreographer.java:893)
    at android.view.Choreographer.doFrame(Choreographer.java:809)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

---
### Environment
* React Native Navigation version: "6.0.1"
* React Native version: "0.61.4"
* Platform(s): Android
* Device info: Version: 9 - Release - Device Huawei ALP-L09

### PR DESCRIPTION
**Pull request by yogevbd**
`push` animation callback was called after the stack children was destroyed by `setStackRoot`.
Fixed by canceling all animations when destroying the stack and when the activity is destroyed.

Fixes #6071

### CODE REVIEW

File: lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt [hunk 1]
```diff
@@ -194,6 +194,15 @@ class StackControllerTest : BaseTest() {
         verify(child1, never()).mergeOptions(any())
     }
 
+    @Test
+    fun setRoot_activityDestroyDuringAnimationShouldNotCrash() {
```
Comment (guyca) [inline lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt:198]: This test has no assertions and it seems like it's name doesn't describe the test correctly.

**Review by guyca — CHANGES_REQUESTED** [review]

**Review by guyca — APPROVED** [review]
