### PR TITLE
RTL Layout

### LINKED ISSUE #3485: [V2] RTL Layout Support
### Issue Description

In many cases our applications need to support __RTL__ languages, __React__ allows to _RTL_ via `I18nManager` API, but __RNN__ does not support any options to deal with layout directions ( Only loves _LTR_ 😢 ).

~~Android Platform:~~
~~In RNN v1 when system language was a RTL  language (like: Persian or Arabic) or simply call `I18nManager.forceRTL(true)`, Everything goes fine, back button shown in right.~~
~~But in RNN v2 Nothing, always left and always LTR, no way to done it.~~

### Steps to Reproduce / Code Snippets / Screenshots

1. Change system language to > `Persian/فارسی` `Arabic`
2. Restart _RNN_ App
3. Push a component to navigator  and __look at navigation__

  > _If works, back button should displayed at right either title._

#### UPDATE: I described workarounds for both _Android_ and _iOS_ platforms in comments.
---
### Environment
* React Native Navigation version: 2.0.2394
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

### PR DESCRIPTION
**Pull request by hadimostafapour**
```javascript
// set direction to RTL layout
Navigation.setDefaultOptions({
      layout: {
          direction: 'rtl'
      }
});
Navigation.setRoot({});
```

```xml
<application
      android:name=".MainApplication"
+     android:supportsRtl="true"
      ...
      android:theme="@style/AppTheme">
```

Fixes #3485

### CODE REVIEW

File: lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java [hunk 1]
```diff
@@ -159,12 +163,28 @@ private Navigator navigator() {
 
 	@NonNull
 	private LayoutFactory newLayoutFactory() {
-		return new LayoutFactory(activity(),
-                navigator().getChildRegistry(),
+
+		NavigationActivity layoutActivity = activity();
```
Comment (guyca) [inline lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java]: This logic shouldn't be here, seems like it's more appropriate to `RootPresenter`.

File: lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/button/NavigationIconResolverTest.java [hunk 2]
```diff
@@ -42,7 +42,7 @@ public void run(Drawable icon) {
 
             }
         });
-        uut.resolve(iconButton(), onSuccess);
+        uut.resolve(iconButton(), 0, onSuccess);
```
Comment (guyca) [inline lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/button/NavigationIconResolverTest.java]: Lets use `View.LAYOUT_DIRECTION_LTR` instead of 0

File: lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/button/NavigationIconResolverTest.java [hunk 3]
```diff
@@ -55,7 +55,7 @@ public void run(Drawable param) {
 
             }
         });
-        uut.resolve(backButton(), onSuccess);
+        uut.resolve(backButton(), 0, onSuccess);
```
Comment (guyca) [inline lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/button/NavigationIconResolverTest.java]: Lets use `View.LAYOUT_DIRECTION_LTR` instead of 0

File: lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java (hunk 1 above)
Comment (hadimostafapour) [reply lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java]: Right, but I'm not sure how can I access to reactContext in `RootPresenter`?

**Comment by danielgindi** [comment]
How about supporting native `LAYOUT_DIRECTION_INHERIT`/`LAYOUT_DIRECTION_LOCALE`?

File: lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java (hunk 1 above)
Comment (guyca) [reply lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java]: Add reactContext as an argument to Navigator.setRoot, then pass it on when calling rootPresenter.setRoot

**Comment by guyca** [comment]
@danielgindi I have no objections, but lets keep this PR small so it's easier to move forward. We can support other flags in a different PR.

**Comment by hadimostafapour** [comment]
@guyca And what about tests? I can't find a way to access reactContext in Tests, should I make them optional parameters?

**Comment by hadimostafapour** [comment]
@guyca Tests are passed but got failed due `Failed to install the following Android SDK packages as some licences have not been accepted.`

**Comment by danielgindi** [comment]
@hadimostafapour not your problem. There were some issues on `master`, try to update your branch

**Comment by mohammadalijf** [comment]
@hadimostafapour hey hadi,
i used react-native's I18nManager to force my application to RTL using 
```javascript
I18nManager.forceRTL(true);
```
everything looks fine except my navigationbar is still LTR and my navigation animations are all LTR.
also there is no Layout option for direction.
am i doing something wrong?

- _react-native_ **0.57.8**
- _react-native-navigation_ **2.13.1**

**Comment by guyca** [comment]
@mohammadalijf Could you please PR the necessary changes? 👍

**Comment by mohammadalijf** [comment]
@guyca ok i created a PR #4847 👍
