### PR TITLE
[Android] Fix title glitch and alignment

### LINKED ISSUE #4571: [v2][Android] Top bar Title Flickering
### Issue Description

While push/pop pages the topBar title blinks. 

demo
_GIF is 5x slower_

Basically same as: #3864

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.6.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

### PR DESCRIPTION
**Pull request by hadimostafapour**
Fixes #4571
and while `setX` used to set __TextView__ position, on device orientation changes __TextView__ `x` remains same and title got a wrong position, this PR also fix this issue.

### CODE REVIEW

File: lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java [hunk 1]
```diff
@@ -101,26 +94,36 @@ public void setSubtitleFontSize(double size) {
...
+        } else if (leftButtonController != null) {
+            view.setX(isRTL ? (getWidth() - view.getWidth()) - getContentInsetStartWithNavigation() : getContentInsetStartWithNavigation());
+        } else {
+            view.setX(isRTL ? (getWidth() - view.getWidth()) - UiUtils.dpToPx(getContext(), DEFAULT_LEFT_MARGIN) : UiUtils.dpToPx(getContext(), DEFAULT_LEFT_MARGIN));
+        }
+    }
+
+    @Override
+    protected void onLayout(boolean changed, int l, int t, int r, int b) {
+        super.onLayout(changed, l, t, r, b);
```
Comment (guyca) [inline lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java]: Can we optimise  this so it realigns the title and subtitle only if `changed == true` ?

File: lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java [hunk 2]
```diff
@@ -48,6 +49,13 @@ public void onViewAdded(View child) {
     public void setTitle(CharSequence title) {
         clearComponent();
         super.setTitle(title);
+        isTitleChanged = true;
+    }
+
+    @Override
+    public void setSubtitle(CharSequence title) {
+        super.setSubtitle(title);
+        isTitleChanged = true;
```
Comment (guyca) [inline lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java]: Shouldn't we create another variable for subtitle?
