### PR TITLE
Deprecate searchBar params in favour of a new standalone searchBar options

### LINKED ISSUE #4093: [V2][iOS] SearchBar missing tint color options + can't change Cancel text color
### Issue Description

- Using the native SearchBar I can not change the color of the Search... background. In my app it has become Dark Blue and I don't know where to change it. Same goes for the Cancel text next to it.

### Steps to Reproduce / Code Snippets / Screenshots

file

---
### Environment
* React Native Navigation version: 2572
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device + Simulator

### PR DESCRIPTION
**Pull request by mateioprea**
We were discussing about moving the search bar params on iOS into a new options object. This will replace the old configuration in favour of the following:

```javascript
options: {
  topBar: {
    searchBar: {
      visible: boolean,
      hideOnScroll: boolean,
      hideTopBarOnFocus: boolean,
      obscuresBackgroundDuringPresentation: boolean,
      backgroundColor: color,
      tintColor: color,
      placeholder: string
    }
  }
}
```

closes #4093

### CODE REVIEW

**Comment by mateioprea** [comment]
Do not merge yet, I still need to add the docs 👍

File: lib/src/commands/Deprecations.ts [hunk 1]
```diff
@@ -11,10 +11,19 @@ export class Deprecations {
...
       this.deprecateBottomTabsVisibility(parentOptions);
     }
+    if (key === 'searchBar' && Platform.OS === 'ios' && typeof parentOptions[key] === 'boolean') {
+      this.deprecateSearchBarOptions(parentOptions);
+    }
   }
 
   public onProcessDefaultOptions(_key: string, _parentOptions: Record<string, any>) {}
 
+  private deprecateSearchBarOptions = once((parentOptions: object) => {
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:21]: @mateioprea Seems like all current `SearchBar` options need to be deprecated: 
```
  searchBar?: boolean;
  searchBarHiddenWhenScrolling?: boolean;
  searchBarPlaceholder?: string;
  searchBarBackgroundColor?: string;
  searchBarTintColor?: string;
  hideNavBarOnFocusSearchBar?: boolean;
```

We should do the following:
1. Warn when a deprecated option is used
2. Options processor should be able to process both old and new api, where the new API takes precedence over the old.
3. Native should only handle the new API

**Review by guyca — CHANGES_REQUESTED** [review]

File: lib/src/commands/Deprecations.ts [hunk 2]
```diff
@@ -1,7 +1,65 @@
 import once from 'lodash/once';
+import get from 'lodash/get';
+import each from 'lodash/each';
 import { Platform } from 'react-native';
 
 export class Deprecations {
+  private deprecatedMethods: Array<{ key: string; showWarning: any }> = [
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:7]: Perhaps rename to `deprecatedOptions`?

```suggestion
  private deprecatedOptions: Array<{ key: string; showWarning: any }> = [
```

File: lib/src/commands/Deprecations.ts [hunk 3]
```diff
@@ -1,7 +1,65 @@
...
+    {
+      key: 'topBar.searchBarHiddenWhenScrolling',
+      showWarning: once((_key: string, parentOptions: object) => {
+        console.warn(
+          `${_key} is deprecated and will be deprecated in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:12]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts [hunk 4]
```diff
@@ -1,7 +1,65 @@
...
+          parentOptions
+        );
+      }),
+    },
+    {
+      key: 'topBar.searchBarPlaceholder',
+      showWarning: once((_key: string, parentOptions: object) => {
+        console.warn(
+          `${_key} is deprecated and will be deprecated in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:21]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts [hunk 5]
```diff
@@ -1,7 +1,65 @@
...
+          parentOptions
+        );
+      }),
+    },
+    {
+      key: 'topBar.searchBarBackgroundColor',
+      showWarning: once((_key: string, parentOptions: object) => {
+        console.warn(
+          `${_key} is deprecated and will be deprecated in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:30]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts [hunk 6]
```diff
@@ -1,7 +1,65 @@
...
+          parentOptions
+        );
+      }),
+    },
+    {
+      key: 'topBar.searchBarTintColor',
+      showWarning: once((_key: string, parentOptions: object) => {
+        console.warn(
+          `${_key} is deprecated and will be deprecated in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:39]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts [hunk 7]
```diff
@@ -1,7 +1,65 @@
...
+          parentOptions
+        );
+      }),
+    },
+    {
+      key: 'topBar.hideNavBarOnFocusSearchBar',
+      showWarning: once((_key: string, parentOptions: object) => {
+        console.warn(
+          `${_key} is deprecated and will be deprecated in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:48]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts [hunk 8]
```diff
@@ -1,7 +1,65 @@
...
+          parentOptions
+        );
+      }),
+    },
+  ];
+
+  public checkForDeprecatedOptions(options: Record<string, any>) {
+    each(this.deprecatedMethods, (method) => {
+      if (get(options, method.key, null)) {
+        method.showWarning(method.key, options);
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts:58]: Rename to `deprecatedOptions` ?
```suggestion
    each(this.deprecatedOptions, (option) => {
      if (get(options, option.key, null)) {
        option.showWarning(option.key, options);
```

File: lib/src/commands/OptionsProcessor.ts [hunk 9]
```diff
@@ -31,6 +31,7 @@ export class OptionsProcessor {
       clone(options),
       (key, parentOptions) => {
         this.deprecations.onProcessOptions(key, parentOptions, commandName);
+        this.deprecations.checkForDeprecatedOptions(parentOptions);
```
Comment (guyca) [inline lib/src/commands/OptionsProcessor.ts:34]: I think that the original intention with `onProcessOptions` was to actually... to check for deprecated options 😅 
Perhaps we can rename `onProcessOptions` to `checkForDeprecatedOptions`?

File: lib/src/commands/OptionsProcessor.ts [hunk 10]
```diff
@@ -134,4 +136,31 @@ export class OptionsProcessor {
       options[key].passProps = undefined;
     }
   }
+
+  private processSearchBar(key: string, value: any, options: Record<string, any>) {
```
Comment (guyca) [inline lib/src/commands/OptionsProcessor.ts:140]: This is great! I'd like to suggest that we handle all deprecated options in a dedicated private method, which we'll be able to delete in the next major version when these options become obsolete. It's a cosmetic change which will increase readability and ease when upgrading RNN.

WDYT?

File: website/docs/api/topBar-searchBar.mdx [hunk 11]
```diff
@@ -0,0 +1,47 @@
+---
```
Comment (guyca) [inline website/docs/api/topBar-searchBar.mdx:1]: @mateioprea We should probably include the `Platform` column to indicate all of these options are iOS specific.

**Review by guyca — CHANGES_REQUESTED** [review]

File: lib/src/commands/OptionsProcessor.ts (hunk 9 above)
Comment (mateioprea) [reply lib/src/commands/OptionsProcessor.ts:34]: Do you think that maybe we can leave this as it is and open a ticket for refactoring the deprecation system that can be open to discussions? :D Otherwise I need to think about this alone and maybe others can have some good suggestions.

File: lib/src/commands/OptionsProcessor.ts (hunk 10 above)
Comment (mateioprea) [reply lib/src/commands/OptionsProcessor.ts:140]: As above^ :D

File: website/docs/api/topBar-searchBar.mdx (hunk 11 above)
Comment (mateioprea) [reply website/docs/api/topBar-searchBar.mdx:1]: Done

**Review by yogevbd — APPROVED** [review]

File: lib/src/commands/OptionsProcessor.ts (hunk 9 above)
Comment (guyca) [reply lib/src/commands/OptionsProcessor.ts:34]: Sure, your call! 👍

File: website/docs/api/options-stack.mdx [hunk 12]
```diff
@@ -114,6 +114,10 @@ Hide the TopBar when a scrolling layout is scrolled.
 | ------- | -------- | -------- |
 | boolean | No       | Both     |
 
+:::warning Deprecation warning
+This option will be deprecated in a future release. Please use the [OptionsSearchBar](topBar-searchBar.mdx) option instead.
```
Comment (danilobuerger) [inline website/docs/api/options-stack.mdx:118]: Shouldnt it be `removed` instead of `deprecated`? Afaik its deprecated now and will be removed in a future release. This applies to the following doc changes as well

**Review by danilobuerger — CHANGES_REQUESTED** [review]
See inline doc cmment

File: website/docs/api/options-stack.mdx (hunk 12 above)
Comment (yogevbd) [reply website/docs/api/options-stack.mdx:118]: Maybe we should define it as `moved`? we can also point to the correct path `topBar.searchBar.*`.

Comment (mateioprea) [reply website/docs/api/options-stack.mdx:118]: @yogevbd @danilobuerger makes sense. how the warning should look like?

Comment (guyca) [reply website/docs/api/options-stack.mdx:118]: @mateioprea I've suggested a few changes above in this matter - the option is currently deprecated and will be removed in a future major version. If you accept my suggestions we can merge the PR :D

**Comment by guyca** [comment]
@yogevbd we might need your help generating the snapshots 🙈

File: website/docs/api/options-stack.mdx (hunk 12 above)
Comment (mateioprea) [reply website/docs/api/options-stack.mdx]: @guyca cannot accept those once I've commited after you've left the comments. I just pushed a new commit. 💯

**Review by guyca — APPROVED** [review]

File: lib/src/commands/Deprecations.ts (hunk 3 above)
Comment (guyca) [inline lib/src/commands/Deprecations.ts]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts (hunk 4 above)
Comment (guyca) [inline lib/src/commands/Deprecations.ts]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts (hunk 5 above)
Comment (guyca) [inline lib/src/commands/Deprecations.ts]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts (hunk 6 above)
Comment (guyca) [inline lib/src/commands/Deprecations.ts]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts (hunk 7 above)
Comment (guyca) [inline lib/src/commands/Deprecations.ts]:
```suggestion
          `${_key} is deprecated and will be removed in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

File: lib/src/commands/Deprecations.ts [hunk 13]
```diff
@@ -11,10 +69,19 @@ export class Deprecations {
...
+    if (key === 'searchBar' && Platform.OS === 'ios' && typeof parentOptions[key] === 'boolean') {
+      this.deprecateSearchBarOptions(parentOptions);
+    }
   }
 
   public onProcessDefaultOptions(_key: string, _parentOptions: Record<string, any>) {}
 
+  private deprecateSearchBarOptions = once((parentOptions: object) => {
+    console.warn(
+      `toggling searchBar visibility using a boolean value will be deprecated in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```
Comment (guyca) [inline lib/src/commands/Deprecations.ts]:
```suggestion
      `toggling searchBar visibility using a boolean value is deprecated and will not be supported in the next major version. For more information see https://github.com/wix/react-native-navigation/issues/6585`,
```

**Review by guyca — CHANGES_REQUESTED** [review]

**Review by guyca — APPROVED** [review]

**Comment by chrise86** [comment]
@guyca I've noticed that on `7.10.0` setting `searchBar.tintColor` changes the cancel button colour, but not the colour of the actual text in the search bar.

See my example where the `tintColor` is set to `#ffffff`:

image
