### PR TITLE
fix for truncated tab item names on ios14

### LINKED ISSUE #6533: Tab bar text cut off and ellipsized on iPadOS 14
### Issue Description

When rendering a tab bar on an iPad running iPadOS Public Beta 6, text labels for tab bar items are truncated. 

### Steps to Reproduce / Code Snippets / Screenshots

IMG_0292

---
### Environment
* React Native Navigation version: Reproduced on playground app built from `master`
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS: iPadOS 14 Public Beta 6
* Device info (Simulator/Device? OS version? Debug/Release?): iPad Pro 11" 2018

### PR DESCRIPTION
**Pull request by bennettk**
this is a fix for when bottom tab items with custom title attributes get truncated on iPads running iOS14.

rnn-before

rnn-after

Fixes #6533

### CODE REVIEW

File: lib/ios/TabBarItemAppearanceCreator.m [hunk 1]
```diff
@@ -13,13 +13,25 @@ + (void)setTitleAttributes:(UITabBarItem *)tabItem titleAttributes:(NSDictionary
     tabItem.standardAppearance.stackedLayoutAppearance.normal.titleTextAttributes = titleAttributes;
     tabItem.standardAppearance.compactInlineLayoutAppearance.normal.titleTextAttributes = titleAttributes;
     tabItem.standardAppearance.inlineLayoutAppearance.normal.titleTextAttributes = titleAttributes;
+    if (@available(iOS 14.0, *)) {
+      UIColor *color = [titleAttributes valueForKey:@"NSColor"];
```
Comment (danilobuerger) [inline lib/ios/TabBarItemAppearanceCreator.m:17]: Please replace `@"NSColor"` with the existing constant `NSForegroundColorAttributeName`

File: lib/ios/TabBarItemAppearanceCreator.m [hunk 2]
```diff
@@ -13,13 +13,25 @@ + (void)setTitleAttributes:(UITabBarItem *)tabItem titleAttributes:(NSDictionary
...
+    }
 }
 
 + (void)setSelectedTitleAttributes:(UITabBarItem *)tabItem selectedTitleAttributes:(NSDictionary *)selectedTitleAttributes {
     [super setSelectedTitleAttributes:tabItem selectedTitleAttributes:selectedTitleAttributes];
     tabItem.standardAppearance.stackedLayoutAppearance.selected.titleTextAttributes = selectedTitleAttributes;
     tabItem.standardAppearance.compactInlineLayoutAppearance.selected.titleTextAttributes = selectedTitleAttributes;
     tabItem.standardAppearance.inlineLayoutAppearance.selected.titleTextAttributes = selectedTitleAttributes;
+    if (@available(iOS 14.0, *)) {
+      UIColor *color = [selectedTitleAttributes valueForKey:@"NSColor"];
```
Comment (danilobuerger) [inline lib/ios/TabBarItemAppearanceCreator.m:30]: Please replace `@"NSColor"` with the existing constant `NSForegroundColorAttributeName`

**Review by danilobuerger — CHANGES_REQUESTED** [review]

File: lib/ios/TabBarItemAppearanceCreator.m (hunk 2 above)
Comment (bennettk) [reply lib/ios/TabBarItemAppearanceCreator.m]: @danilobuerger ah, good point-- updated. thanks!

**Comment by danilobuerger** [comment]
@yogevbd @bennettk This is causing a regression: Other non color styles (i.e. fontstyle, fontfamily, fontweight) are not being applied anymore on ipad on iOS 14.

**Comment by yogevbd** [comment]
@danilobuerger make sense.. my bad. I missed that it replaced the whole titleTextAttributes object. reverting

**Comment by guyca** [comment]
@yogevbd Perhaps this is a good opportunity to improve our screenshot test coverage and test BottomTabs scenarios as well!

**Comment by guyca** [comment]
@bennettk 

> @yogevbd @bennettk This is causing a regression: Other non color styles (i.e. fontstyle, fontfamily, fontweight) are not being applied anymore on ipad on iOS 14.

@bennettk Have you managed to reproduce this regression @danilobuerger found?
